name: App Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ci:
    uses: TestingMigration-Lux/shared-workflows/.github/workflows/python-ci.yml@main
    with:
      python-version: '3.11'
